### PR TITLE
Update asciibinder image

### PR DESCRIPTION
**Pull request by aireilly**
1. Reduce image size (currently 182 MB, was ~ 1GB) - `asciibinder.Dockerfile`.  Implements suggestion in https://github.com/openshift-cs/docs-builder/issues/19 @gaurav-nelson @wgordon17 PTAL
2. Created `openshift-docs-build.Dockerfile` which includes python tools to do portal builds out of the box.

:tophat: tip to @gaurav-nelson for the Dockerfile suggestion.

@wgordon17 when you merge this, can you update `quay.io/openshift-cs/asciibinder` image to be built from the `asciibinder.Dockerfile` please. Can you also create a new `quay.io/openshift-cs/openshift-docs-build` from `openshift-docs-build.Dockerfile` thanks.

### CODE REVIEW

**Comment by aireilly** [comment]
Seeing a strange error: 
```
$ podman run --network=host --rm -it -v `pwd`:/docs:Z 40012c26d6fcc95ab41887d96fd372ed66d174eac57d16e484c9947bafc2f494 python3 build_for_portal.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.13 --no-upstream-fetch
/docs/tmp6l1_kmc8.swp
Cleaning the drupal-build directory
Building the drupal files
Processing welcome
Processing release_notes
Processing getting_started
Processing architecture
Processing installing
An include file wasn't found: https://raw.githubusercontent.com/openshift/installer/masteruser/aws/tested_instance_types_x86_64.md
```

However,
```
$ podman run --network=host --rm -it -v `pwd`:/docs:Z 40012c26d6fcc95ab41887d96fd372ed66d174eac57d16e484c9947bafc2f494 wget https://www.google.com
Connecting to www.google.com ([2a00:1450:400b:c00::6a]:443)
saving to 'index.html'
index.html           100% |*********************************************************************************| 19027  0:00:00 ETA
'index.html' saved
```

**Comment by aireilly** [comment]
> Seeing a strange error:
> 
> ```
> $ podman run --network=host --rm -it -v `pwd`:/docs:Z 40012c26d6fcc95ab41887d96fd372ed66d174eac57d16e484c9947bafc2f494 python3 build_for_portal.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.13 --no-upstream-fetch
> /docs/tmp6l1_kmc8.swp
> Cleaning the drupal-build directory
> Building the drupal files
> Processing welcome
> Processing release_notes
> Processing getting_started
> Processing architecture
> Processing installing
> An include file wasn't found: https://raw.githubusercontent.com/openshift/installer/masteruser/aws/tested_instance_types_x86_64.md
> ```
> 
> https://raw.githubusercontent.com/openshift/installer/masteruser/aws/tested_instance_types_x86_64.md
> 
> The file is live and correct.
> 
> However,
> 
> ```
> $ podman run --network=host --rm -it -v `pwd`:/docs:Z 40012c26d6fcc95ab41887d96fd372ed66d174eac57d16e484c9947bafc2f494 wget https://www.google.com
> Connecting to www.google.com ([2a00:1450:400b:c00::6a]:443)
> saving to 'index.html'
> index.html           100% |*********************************************************************************| 19027  0:00:00 ETA
> 'index.html' saved
> ```

Error was caused by ``pwd`:/docs:Z` somehow replacing /docs in ths build? :shrug: 

```
https://raw.githubusercontent.com/openshift/installer/master/docs/user/aws/tested_instance_types_x86_64.md

>>>

https://raw.githubusercontent.com/openshift/installer/masteruser/aws/tested_instance_types_x86_64.md
```

**Comment by aireilly** [comment]
Both images verified locally (`openshift-docs-build.Dockerfile`): 
```
┌───── ~/openshift-docs (main)
$ podman run --network=host --rm -it -v `pwd`:/openshift-docs-build:Z 54f2a7dc7670579acf4961e68bc9b033d2e345bd227d1cea4fe42c1b67489fbb python3 build_for_portal.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.13 --no-upstream-fetch
/openshift-docs-build/tmpfy4nod75.swp
Cleaning the drupal-build directory
Building the drupal files
Processing welcome
Processing release_notes
Processing getting_started
Processing architecture
Processing installing
Processing post_installation_
...
```

`asciibinder.Dockerfile`:
```
┌───── ~/openshift-docs (main)
$ podman run --rm -it -v `pwd`:/docs:Z a11cd09484e2 asciibinder build
Building all distributions.
WARN: The following branches do not exist in your local git repo:
- build-docs-1.0
- enterprise-3.0
- enterprise-3.1
- enterprise-3.10
...
```

**Comment by wgordon17** [comment]
This is great @aireilly, thank you! Would you mind also updating the README with relevant commands/usage? https://github.com/openshift-cs/docs-builder/blob/main/asciibinder/README.md

**Comment by aireilly** [comment]
@wgordon17 Done.

**Comment by aireilly** [comment]
@wgordon17 few tweaks. Should be good to merge now thanks.

**Pull request merged**
